### ISSUE TITLE
Drone does not work fine

### ISSUE THREAD

**Issue by KaiMan123** [sw6y15/HKEvent#10]
We had tried to run the code for AI model with DJI drone and we found an obvious time delay which is similar with the problem happened in the AI model workshop in HKU (10/1 Thur). May I know how to fix this problem? Will this problem causing the AI prediction fail? Moreover, we tested our model in Microsoft and we cannot get the red frame for final sample code with the use of DJI drone, but we can get red frame with a capture photo in other sample code without DJI drone using the same AI model. Could you enlighten us with any possible cause to this problem?
Thank you.

**Comment by LiangJy123** [comment]
###### The DJIVideoParser decode the H264 stream to pictures, and if this process become slowly ,there will be a time delay.  This process uses the CPU, so it also has a relation with the performance of the computer.We're also trying to solve this delay problem.

###### Sometimes, you can run the app without VS2017, the delay will be reduced,because VS2017 consumes a lot of system resources when it's in a debug state.You can see and run your app at the Start menu.
![image](https://user-images.githubusercontent.com/13048899/51291926-ddedf000-1a43-11e9-96e3-5e54c476ab3a.png)


###### But this problem does not cause AI prediction to fail.If you can see the picture on the interface, it means that AI can also get input correctly.
