### ISSUE TITLE
Still can not build the S2 in my own computer

### ISSUE THREAD

**Issue by AK51** [sw6y15/HKEvent#17]
Hi,

I saw in the student computer that they use Microsoft.NETCore.UniversalWindowsPlatform 6.0.8 only.
If possible, please show me the print screen of your computer and I can duplicate the environment. Thx

Hint: The original Assembly name is not DJIUWPDEMO and the Default namespace is not DJIDemo. (It was UWPSampleCode...) I wonder if the file from aka.ms/aidronefiles is the same as what the student has. Thx

Hint: Before I upgrade the win to 17763, I can still see a big cross window after build (still not a successful build)

![image](https://user-images.githubusercontent.com/8468724/51433968-8db89d00-1c92-11e9-9e0b-2b08a501cce2.png)
![image](https://user-images.githubusercontent.com/8468724/51433977-bb9de180-1c92-11e9-8417-22bff9d42d26.png)

![image](https://user-images.githubusercontent.com/8468724/51433979-cc4e5780-1c92-11e9-983d-cd5932ad5a5b.png)

![image](https://user-images.githubusercontent.com/8468724/51433994-2cdd9480-1c93-11e9-801b-16343bb9e23f.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Attend date**
Provide the information of when you attend our workshop.

**Additional context**

**Comment by AK51** [comment]
Here is what I see right after I unzip the S2. Will it be the S2 zip file problem? Thx
Is it ok if you can zip your project and let me try it? Thx

![image](https://user-images.githubusercontent.com/8468724/51434149-5697bb00-1c95-11e9-962d-3d86c9403758.png)

![image](https://user-images.githubusercontent.com/8468724/51434155-69aa8b00-1c95-11e9-9273-55235a249f45.png)
![image](https://user-images.githubusercontent.com/8468724/51434161-8a72e080-1c95-11e9-8dfc-ec6f73df0801.png)

**Comment by LiangJy123** [comment]
OK，nice to see you again and sorry for late. 
Recently very busy may reply a little slower, but I will provide help until you solve this problem.
That's my references versions.
![image](https://user-images.githubusercontent.com/13048899/51508898-3a7d5080-1e32-11e9-91ad-ca685461ed3c.png)

I can see in your picture and get the problem is "Nuget restore failed".
When you nuget a reference , you can see it in your .csproj file
```
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.1.9</Version>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json">
      <Version>12.0.1</Version>
    </PackageReference>
    <PackageReference Include="Win2D.uwp">
      <Version>1.23.0</Version>
    </PackageReference>
  </ItemGroup>
```
But the reference's runtimes wasn't in your solution. They are in your %userfolder%\\.nuget\packages


When we move a solution to another computer and build it ,the .csproj file tell to VS that it needs the runtimes .VS try to get their runtimes  in local , then if runtimes is not in local ,VS try to restore online.

So if restore failed ,they may build failed.


I hope it can help you.

**Comment by AK51** [comment]
Do you think the file in aka.ms/aidronefiles is the same as the project in the students computer? Thx

**Comment by LiangJy123** [comment]
The final sample code may be different. Because  the os of surface books we used only have Windows SDK v17763.
Others are the same.

**Comment by AK51** [comment]
Is it possible to share the code with me?
Are you in HK? I can visit your office and I believe we can solve the problem very quickly. Thx

**Comment by LiangJy123** [comment]
of course , I can share .You can give me your email.
I'm in shenzhen , so....

**Comment by AK51** [comment]
ak51@hku.hk, thx
